feat(tests): More readable output on failure
enarx/enarx-keepldr pull request #148
Opened 2020-11-11 12:38 UTC by haraldh

The integration tests output very long `assert_eq` comparisons, if the
output doesn't match the expected. To reduce the clutter, only use
`assert_eq` if the size is smaller than 100.

Also, in the case of only expected stdout, print out any stderr received,
to help debug any failures.

Signed-off-by: Harald Hoyer <harald@redhat.com>

2020-11-11 14:56 UTC, lkatalin approved these changes
LGTM, thanks.

2020-11-11 15:50 UTC, connorkuehl requested changes
I think we should throw `100` into a const and refer to the const variable

2020-11-12 10:32 UTC, haraldh commented
Revised the whole patch again for more readability.

2020-11-12 18:22 UTC, connorkuehl approved these changes

2020-11-12 19:05 UTC, merged