Add 'LABEL' to workflow
enarx/enarx-keepldr pull request #162
Opened 2020-11-11 20:50 UTC by matt-ross16

enarx/bot#160

Adding this LABEL property to the workflow file should allow for distinction between badges on the enarx/bot README.

2020-11-11 21:41 UTC, haraldh requested changes
this is an unresolved merge

2020-11-11 21:58 UTC, matt-ross16 commented
Thanks for pointing this out @haraldh 
Should be fixed up now

2020-11-11 21:58 UTC, mbestavros approved these changes
LGTM!

2020-11-12 06:07 UTC, haraldh approved these changes

2020-11-12 06:24 UTC, merged