Prepare some small changes for SGX attestation
enarx/enarx-keepldr pull request #163
Opened 2020-11-11 22:12 UTC by lkatalin

We will need an updated version of the SGX dependency and we'll need to use Intel's `aesm-proto` file to generate Rust structures during build.

2020-11-12 09:01 UTC, haraldh requested changes

2020-11-12 09:01 UTC, haraldh commented on src/protobuf/mod.rs
> +//! aesm-proto.proto during build.
```suggestion
//! Provides all generated protobuf modules

include!(concat!(env!("OUT_DIR"), "/protos/mod.rs"));
```

This then includes the generated protobuf modules.

You will then have to use `crate::protobuf::aesm_proto`.

2020-11-13 16:32 UTC, lkatalin commented on build.rs
Thanks. I'm looking for info on `gen_mod_rs` but it's not very obvious. I assume it lets you name the output `mod.rs`, which is what I was trying to do.

2020-11-13 16:33 UTC, lkatalin commented
I pulled the error handling for `create_dir()` out into its own function since we use it several times.

2020-11-13 16:48 UTC, lkatalin commented on build.rs
Yeah, I see from the link this is how it's normally done: "And for now, you may generate that mod.rs in OUT_DIR file from build.rs, and include generated mod.rs from the src directory."

2020-11-13 19:17 UTC, haraldh approved these changes

2020-11-16 17:51 UTC, connorkuehl approved these changes
I did not confirm the correctness of Intel's proto file

2020-11-16 18:06 UTC, merged