fix: validate SEV cert chain
enarx/enarx-keepldr pull request #294
Opened 2021-01-19 08:26 UTC by haraldh

To be sure, `/var/cache/amd-sev/chain` exists and is valid, add some
tests.

Signed-off-by: Harald Hoyer <harald@redhat.com>

2021-01-19 14:56 UTC, connorkuehl requested changes

2021-01-19 14:56 UTC, connorkuehl commented on .github/workflows/test.yml
> +          stat /var/cache/amd-sev/chain
Is this needed?

2021-01-19 14:56 UTC, connorkuehl commented on .github/workflows/test.yml
> +          cargo install sevctl
`sevctl` isn't pushed to crates.io. You'll have to install via a git revision.

```console
cargo install --git https://github.com/enarx/sevctl
```

Can use the `--rev` switch to pin a certain commit to install from.

2021-01-19 14:56 UTC, connorkuehl commented on tests/integration_tests.rs
> +}
Use the [`cached_chain` module](https://github.com/enarx/sev/blob/master/src/util/cached_chain.rs#L64) to adhere to the Enarx search path for the cert.

2021-01-21 13:38 UTC, haraldh commented
Ok, I completely revamped the whole thing.
`enarx-keepldr` will check for a valid certificate chain and print diagnostics, why the backend couldn't be used.

2021-01-21 14:37 UTC, haraldh commented
and revamped again

2021-01-22 21:20 UTC, connorkuehl commented
As an alternative to managing the thread's join handle, what do you think of just changing the unwrap behavior in `unattested_launch::launch` to a custom `unwrap_or_exit` like we had in `sevctl` for a while?

2021-01-25 14:54 UTC, npmccallum commented
@haraldh Can you rebase this so tests work?

2021-01-25 15:11 UTC, haraldh commented
@npmccallum done

2021-01-25 16:09 UTC, npmccallum approved these changes

2021-01-25 16:13 UTC, mbestavros approved these changes

2021-01-25 16:36 UTC, connorkuehl approved these changes

2021-01-25 16:37 UTC, npmccallum approved these changes

2021-01-25 16:38 UTC, merged