Fix C warning
enarx/enarx-keepldr pull request #316
Opened 2021-01-27 16:45 UTC by lkatalin

Apparently the C compiler doesn't like the for loop the other way.

2021-01-27 16:57 UTC, haraldh requested changes

2021-01-27 16:57 UTC, haraldh commented on tests/bin/sgx_get_att_quote.c
> +    for (; i < 32; i++)
```suggestion
    for (i = 0; i < 32; i++)
```

2021-01-27 17:04 UTC, lkatalin commented on tests/bin/sgx_get_att_quote.c
> +    for (; i < 32; i++)
That looks better to me also.

2021-01-27 17:32 UTC, haraldh approved these changes

2021-01-28 09:03 UTC, ueno approved these changes

2021-01-28 09:21 UTC, merged