Asm fixes
enarx/enarx-keepldr pull request #445
Opened 2021-08-16 12:32 UTC by haraldh

Recent nightly needs some asm fixes.

2021-08-16 14:58 UTC, npmccallum requested changes

2021-08-16 14:58 UTC, npmccallum commented on internal/shim-sgx/src/enclave.rs
> +    #[allow(named_asm_labels)]
We probably want to `warn` here instead of `allow`. This is one case where warning makes sense because we want to know when the problem is resolved.

2021-08-16 14:59 UTC, npmccallum commented
@haraldh Can you split the local named label issues to a separate PR? I can approve the other stuff.

2021-08-16 15:28 UTC, haraldh commented
> @haraldh Can you split the local named label issues to a separate PR? I can approve the other stuff.

https://github.com/enarx/enarx-keepldr/pull/446

2021-08-16 17:04 UTC, npmccallum commented
> > @haraldh Can you split the local named label issues to a separate PR? I can approve the other stuff.
> 
> #446

You need to remove them from this PR so we can merge this.

2021-08-17 08:32 UTC, haraldh commented
> > > @haraldh Can you split the local named label issues to a separate PR? I can approve the other stuff.
> > 
> > 
> > #446
> 
> You need to remove them from this PR so we can merge this.

We need all the fixes for the CI to pass.

2021-08-17 14:09 UTC, closed without merging