shim-sev: Avoid mapping unencrypted and encrypted pages to the same physical memory
enarx/enarx-keepldr pull request #76
Opened 2020-10-13 14:26 UTC by haraldh

Map 0x00_0000 - 0x20_0000 from encrypted to unencrypted.

Also unmap the encrypted identity map address range
0x20_0000 - 0x40_0000
0x40_0000 - 0x60_0000
after completely switching to kernel virtual address space.

Also move the page tables `.data` from assembler to rust code.

Also reformat the assembler code a little bit for readability.

Signed-off-by: Harald Hoyer <harald@redhat.com>

2020-10-13 17:17 UTC, ambaxter approved these changes
lgtm

2020-10-13 19:48 UTC, connorkuehl requested changes

2020-10-13 19:48 UTC, connorkuehl commented on internal/shim-sev/src/pagetables.rs
> +/// an aligned page table page
```suggestion
/// A page-aligned Page Table.
```

2020-10-13 19:48 UTC, connorkuehl commented on internal/shim-sev/src/pagetables.rs
> +    let step: u64 = 0x40000000;
Same comment about `bytes!` as above

2020-10-14 07:12 UTC, haraldh commented on internal/shim-sev/src/pagetables.rs
> +/// an aligned page table page
fixed

2020-10-14 07:12 UTC, haraldh commented on internal/shim-sev/src/pagetables.rs
> +    let step: u64 = 0x200000;
yes

2020-10-14 07:12 UTC, haraldh commented on internal/shim-sev/src/pagetables.rs
> +    let step: u64 = 0x40000000;
kind of

2020-10-14 13:33 UTC, npmccallum requested changes
This commit does three distinct things, but I don't see an obvious dependency between them such that they need to be in a single commit. Can you split this up?

2020-10-15 07:15 UTC, haraldh commented
> This commit does three distinct things, but I don't see an obvious dependency between them such that they need to be in a single commit. Can you split this up?

@npmccallum done

2020-10-19 15:01 UTC, npmccallum requested changes
Everything looks good except for the commit messages which need to follow:
https://chris.beams.io/posts/git-commit/

2020-10-21 13:40 UTC, haraldh commented
> Everything looks good except for the commit messages which need to follow:
> https://chris.beams.io/posts/git-commit/

Extended the commit messages and reworded the initial comment in this PR.

2020-10-22 15:02 UTC, npmccallum approved these changes

2020-10-22 15:05 UTC, connorkuehl approved these changes

2020-10-22 15:06 UTC, merged